version: "3"
services:
  fizzbuzz:
    image: golang:1.13.4-alpine
    ports:
      - 1337:1337
      - 6060:6060
    volumes:
      - .:/go/src/fizzbuzz
      - ./config:/go/config
      - ./src:/go/src
      - ./scripts:/go/scripts
    command: /bin/sh -c "sh ./scripts/build.sh && ./bin/fizzbuzz -config ./config/fizzbuzz/fizzbuzz.json"